<?php
/**
 * Created by PhpStorm.
 * User: POE10
 * Date: 03/05/2019
 * Time: 16:16
 */

namespace Drupal\hello\Form;


use Drupal\Core\Form\ConfigFormBase;
use Drupal\Core\Form\FormStateInterface;

class ConfigForm extends ConfigFormBase
{
    public function getFormId()
    {
        // TODO: Implement getFormId() method.
        return 'admin_form';
    }
    protected function getEditableConfigNames()
    {
        // TODO: Implement getEditableConfigNames() method.
        return ['hello.settings'];
    }

    public function buildForm(array $form, FormStateInterface $form_state)
    {   $form['select'] = array(
        '#type' => 'select',
        '#options' => array(
            '0' => 'Never purge',
            '1' => '1 jour',
            '2' => '2 jours',
            '7' => '7 jours',
            '14' => '14 jours',
            '30' => '30 jours',
        ),
        '#title' => 'How long to keep user activity statistics',
        '#default_value' => $this->config('hello.settings')->get('purge_days_number'),
    );
        return parent::buildForm($form, $form_state); // TODO: Change the autogenerated stub
    }

    public function submitForm(array &$form, FormStateInterface $form_state)
    {
        parent::submitForm($form, $form_state); // TODO: Change the autogenerated stub

        $value = $form_state->getValue('select');
        $this->config('hello.settings')->set('purge_days_number', $value)->save();
    }
}
