<?php

/**
 * @file
 * Contains perf.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function perf_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the perf module.
    case 'help.page.perf':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Manage a block with a placeholder render array') . '</p>';
      return $output;

    default:
  }
}
